# Generated by Django 5.0.7 on 2024-08-07 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_payment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
